// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgF9roOa1t4z7dUY7hHiZl1T1zI6nQb3c',
    appId: '1:91687240852:web:e44ccc4cbbd063deab2081',
    messagingSenderId: '91687240852',
    projectId: 'social-app-60f37',
    authDomain: 'social-app-60f37.firebaseapp.com',
    storageBucket: 'social-app-60f37.firebasestorage.app',
    measurementId: 'G-0SJ215FLKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUGUkN8cv2k3x5sCtCnSMbSU4cMgOuxxU',
    appId: '1:91687240852:android:1a56b1cf4df3d94aab2081',
    messagingSenderId: '91687240852',
    projectId: 'social-app-60f37',
    storageBucket: 'social-app-60f37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWE_5cm91fdRfqW4ZD73oA9S6C8BMIrfo',
    appId: '1:91687240852:ios:34fcdcc7f9973bdcab2081',
    messagingSenderId: '91687240852',
    projectId: 'social-app-60f37',
    storageBucket: 'social-app-60f37.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWE_5cm91fdRfqW4ZD73oA9S6C8BMIrfo',
    appId: '1:91687240852:ios:34fcdcc7f9973bdcab2081',
    messagingSenderId: '91687240852',
    projectId: 'social-app-60f37',
    storageBucket: 'social-app-60f37.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgF9roOa1t4z7dUY7hHiZl1T1zI6nQb3c',
    appId: '1:91687240852:web:a7c183097afc2b9cab2081',
    messagingSenderId: '91687240852',
    projectId: 'social-app-60f37',
    authDomain: 'social-app-60f37.firebaseapp.com',
    storageBucket: 'social-app-60f37.firebasestorage.app',
    measurementId: 'G-C9C1ZCF3HC',
  );
}
